# ========================================================================================
# Skoarmantics - Generated by Code_Skoarmantics_Py on 2014-05-05 21:29:46 for Python 3.3.2
# ========================================================================================




# -
# 
# -
def musical_keyword_misc(skoar, noad):
    pass


def meter_sig_prime(skoar, noad):
    pass


def optional_carrots(skoar, noad):
    pass


def meter(skoar, noad):
    pass


def ottavas(skoar, noad):
    pass


def msg(skoar, noad):
    pass


def pedally(skoar, noad):
    pass


def dynamic(skoar, noad):
    pass


def meter_beat(skoar, noad):
    pass


def coda(skoar, noad):
    pass


def markers(skoar, noad):
    pass


def cthulhu(skoar, noad):
    pass


def dal_goto(skoar, noad):
    pass


def accidentally(skoar, noad):
    pass


def listy(skoar, noad):
    pass


def skoaroid(skoar, noad):
    pass


def assignment(skoar, noad):
    pass


def beat(skoar, noad):
    pass


def boolean(skoar, noad):
    pass


def stmt(skoar, noad):
    pass


def meter_symbolic(skoar, noad):
    pass


def msg_chain_node(skoar, noad):
    pass


def meter_ass(skoar, noad):
    pass


def clef(skoar, noad):
    pass


