from datetime import datetime


class Voice:

    def __init__(self):
        self.language = ""
        self.cmt_char = ""
        self.ext = ""
        self.tab = 0

    def cmt(self, words):
        pref = self.tabby + self.cmt_char + " "
        x = "\n" + pref
        words = pref + words.replace("\n", x)
        print(words)

    def code_raw(self, code):
        print(code, end="")

    def file_header(self, filename, spell):
        self.cmt(box("{filename}{ext} - Generated by {spell} on {date} for {language}".format(
            filename=filename, ext=self.ext, spell=spell, date=str(datetime.now()), language=self.language), "="))

    def wee_header(self, text):
        self.cmt(box(text))

    def newline(self, n=1):
        for i in range(0, n):
            print("")

    def code_line(self, line, end="\n"):
        print(self.tabby + line, end=end)

    @property
    def tabby(self):
        return ("{:>" + str(self.tab * 4) + "}").format(" ")


def box(text, char="-"):
    n = len(text)

    line = ("{:" + char + ">" + str(n) + "}").format(char)

    return "{line}\n{text}\n{line}".format(line=line, text=text)


SC = Voice()

SC.language = "SuperCollider 3.6"
SC.cmt_char = '//'
SC.ext = ".sc"


PY = Voice()

PY.language = "Python 3.4"
PY.cmt_char = '#'
